required:
  genome: "test/data/GRCh38.primary_assembly.chr22.fa"
  input: ""
  outdir: "test/results/chr22"
optional:
  busco_downloads: "test/busco_downloads"
  lineage: "eutheria_odb10"
  flanking_region: 1000
  test_size: 5000
  species_name: "new_specie"
resources:
  big:
    cpus: 5
    mem: 32G
    time: 24:00:00
  small:
    cpus: 2
    mem: 16G
    time: 12:00:00
  