mandatory:
  genome: ""
  input: ""
  outdir: ""
optional:
  lineage: "eutheria_odb10"
  flanking_region: 1000
  test_size: 5000
resources:
  big:
    cpus: 8
    mem: 32G
    time: 24:00:00
  small:
    cpus: 4
    mem: 16G
    time: 12:00:00
  