required:
  genome: ""
  input: ""
  outdir: "results"
  toolsdir: "/home/pabloati/Programs/lr_annotation"
  samples_setup: "data/experiment_setup.tsv"
isoseq:
  primers: "data/original_primers.fasta"
  primers_to_samples: "primers_sample.csv"
augustus:
  prediction: evidence_driven
  reference_gtf: "data/mm39.ncbiRefSeq.gtf"
  species_name: "mouse_trial"
  utr: True
  mode: split
qc:
  omark_db: Metazoa
ab_initio:
  busco_downloads: "busco_downloads"
  lineage: "eutheria_odb10"
  flanking_region: 1000
  test_size: 5000
resources:
  big:
    cpus: 10
    mem: 20G
    time: 24h
    qos: long
  busco:
    cpus: 30
    mem: 60G
    time: 120h
    qos: long
  small:
    cpus: 2
    mem: 8G
    time: 2h
    qos: short
  small_bigMem:
    mem: 20G
  medium:
    cpus: 8
    mem: 12G
    time: 10h
    qos: short
