required:
  genome: "test/data/GRCh38.primary_assembly.chr22.fa"
  input: ""
  outdir: "test/results/chr22"
  toolsdir:
  samples_setup: ""
isoseq:
  primers: "data/original_primers.fasta"
  primers_to_samples: "primers_sample.csv"
  prediction: evidence_driven
  reference_gtf: data/mm39.ncbiRefSeq.gtfl
optional:
  busco_downloads: "test/busco_downloads"
  lineage: "eutheria_odb10"
  flanking_region: 1000
  test_size: 5000
  species_name: "new_specie"
resources:
  big:
    cpus: 10
    mem: 32G
    time: 24:00:00
    qos: long
  busco:
    cpus: 40
    mem: 64G
    time: 240:00:00
    qos: long
  medium:
    cpus: 8
    mem: 16G
    time: 8:00:00
  small:
    cpus: 2
    mem: 8G
    time: 2:00:00
    qos: short
  small_bigMem:
    mem: 20G
  